### ISSUE TITLE
如何正确地进行机房惨案 | code004's Blog

### ISSUE THREAD

**Issue by code004Accepted** [code004Accepted/blog-comment#11]
https://code004.ml/how-to-jfca/#more 

 当你的同学忘了锁电脑时… 本文作者不对任何因使用本页代码而造成的悲剧/毒打/报复等负责。任何因以下行为造成的后果均与 本站/本人/版权说明中的原创者 无关。

**Comment by Alpha1022** [comment]
那个，`%0|%0` 应该要写在一个 bat 文件里执行才行。

**Comment by code004Accepted** [comment]
> @Alpha1022
> 那个，`%0|%0` 应该要写在一个 bat 文件里执行才行。

感谢，原文作者把它放到脚本里了 所以我忘了多试一次qwq

**Comment by code004Accepted** [comment]
> @Alpha1022
> 那个，`%0|%0` 应该要写在一个 bat 文件里执行才行。

我昨晚试了一下，结果电脑崩了，一直提示 正在准备Windows qwq 现已通过系统还原解决

**Comment by extmool** [comment]
请注意您的行为已经违反了CC BY-NC-SA 4.0 （不可演绎）许可协议：转载时不允许修改。所以，请注意，此篇博文可能是违法的。

**Comment by code004Accepted** [comment]
> @extmool
> 请注意您的行为已经违反了CC BY-NC-SA 4.0 （不可演绎）许可协议：转载时不允许修改。所以，请注意，此篇博文可能是违法的。

感谢您的回复，但是：

1. 请问根据上述协议，我能否先将您的原文写在前面，再进行批注？
2. 您好像并未在您的blog文章及首页写明您的博客遵循此协议...

如果您认为有必要，我一定会尽快删除或反修改此篇博文，感谢您的提醒。

PS：8月1~3日我不会有时间进行回复，所以可能必须得等到8月4日我才有可能对此文章进行修改或删除。

十分感谢dalao能抽出时间看蒟蒻的小站，蒟蒻一定会100%遵循您的要求。%%%

**Comment by MoveToEx** [comment]
请注意，您转载[如何优雅地机惨别人 for Win](https://movetoex.github.io/posts/b871c09cf73bca69.html)文章的行为已经违反CC BY-NC-**ND(禁止演绎)**，您不得发布修改后的文章。

**Comment by code004Accepted** [comment]
@extmool

没错，我又检查了一遍，好像您的博客中并没有提到遵循任何协议。尤其在我阅读文章时我是没有看到协议的，所以此篇博文应该是合法的。还有，除非您能给出我阅读博文时（按本文发表时间计算）您博客中有提到协议，否则此博文就是合法的（不管您现在是否更改）

证据：![1.png](https://i.loli.net/2019/08/01/5d4273b65d44671122.png)

**Comment by code004Accepted** [comment]
先暂时删除此博文，请各位转到Github Issues进行讨论。

https://github.com/code004accepted/blog-comment

**Comment by code004Accepted** [comment]
@MoveToEx 您的文章页面有协议声明，蒟蒻没看到，实在抱歉，博文已删除。
@extmool 您的博客并未有协议声明，建议您尽快加上，避免产生其他影响。博文已删除

以上，实在对不起各位dalao，以后不会再随意修改各位的文章。谢谢

**Comment by code004Accepted** [comment]
@MoveToEx @extmool 经过测试，现在文章页面已经404。实在对不起各位dalao了...

**Comment by code004Accepted** [comment]
此文章可能会在3天后被修改，再重新被公开，会删除里面与 @MoveToEx 文章相关的内容，但不一定删除 @extmool 文章中的内容。具体到时候再协商。

**Comment by code004Accepted** [comment]
@MoveToEx @extmool 以上

**Comment by code004Accepted** [comment]
> 请注意您的行为已经违反了CC BY-NC-SA 4.0 （不可演绎）许可协议：转载时不允许修改。所以，请注意，此篇博文可能是违法的。

您好，经过核实

1. 您的博客中至今仍未给出相关证明
2. CC BY-NC-SA协议中并没有提及不可演绎。SA表示ShareAlike，官网原文如下：

>You let others copy, distribute, display, perform, and modify your work, as long as they distribute any modified work on the same terms. If they want to distribute modified works under other terms, they must get your permission first.

也就是说，我可以随意修改您的文章，但在发表时必须遵守相同协议，我做到了，所以我完全有权发表文章。

以上

**Comment by MoveToEx** [comment]
> > 请注意您的行为已经违反了CC BY-NC-SA 4.0 （不可演绎）许可协议：转载时不允许修改。所以，请注意，此篇博文可能是违法的。
> 
> 您好，经过核实
> 
> 1. 您的博客中至今仍未给出相关证明
> 2. CC BY-NC-SA协议中并没有提及不可演绎。SA表示ShareAlike，官网原文如下：
> 
> > You let others copy, distribute, display, perform, and modify your work, as long as they distribute any modified work on the same terms. If they want to distribute modified works under other terms, they must get your permission first.
> 
> 也就是说，我可以随意修改您的文章，但在发表时必须遵守相同协议，我做到了，所以我完全有权发表文章。
> 
> 以上

---

根据您引用的片段：

> If they want to distribute modified works under other terms, they **must get your permission first**.

如果我的理解没有出现错误，您必须将修改后的转载文章标记为同样使用 CC BY-NC-SA 4.0 ，但是您的博客似乎在侧边栏指出统一使用 CC BY-NC-ND 4.0 （[页面归档](https://web.archive.org/web/20190908123746/https://code004.ml/)，保存于 UTC+8 2019-09-08 20:37:46），所以，您的转载行为依然是不被允许的  

另外，截至本评论发送之时，@extmool 的博客使用 CC BY-NC-ND 4.0 协议，以下是该协议的 ND 部分：  
> NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

**Comment by code004Accepted** [comment]
> > > 请注意您的行为已经违反了CC BY-NC-SA 4.0 （不可演绎）许可协议：转载时不允许修改。所以，请注意，此篇博文可能是违法的。
> > 
> > 
> > 您好，经过核实
> > 
> > 1. 您的博客中至今仍未给出相关证明
> > 2. CC BY-NC-SA协议中并没有提及不可演绎。SA表示ShareAlike，官网原文如下：
> > 
> > > You let others copy, distribute, display, perform, and modify your work, as long as they distribute any modified work on the same terms. If they want to distribute modified works under other terms, they must get your permission first.
> > 
> > 
> > 也就是说，我可以随意修改您的文章，但在发表时必须遵守相同协议，我做到了，所以我完全有权发表文章。
> > 以上
> 
> 根据您引用的片段：
> 
> > If they want to distribute modified works under other terms, they **must get your permission first**.
> 
> 如果我的理解没有出现错误，在未取得 @extmool 授权的情况下，您必须将修改后的转载文章标记为同样使用 CC BY-NC-SA 4.0 ，但是您的博客似乎在侧边栏和每篇文章底部明确指出使用 CC BY-NC-ND 4.0 （[页面归档](https://web.archive.org/web/20190908123746/https://code004.ml/) 创建于 UTC+8 2019-09-08 20:37:46），所以，您的转载行为依然是不被允许的
> 
> 另外，截至本评论发送之时，@extmool 的博客使用 CC BY-NC-ND 4.0 协议，以下是该协议的 ND 部分：
> 
> > NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.
> 
> 关于 extmool's Blog 上的共享协议，参见 [关于 | extmool's Blog](https://extmool.github.io/about/#%E5%85%AC%E5%91%8A%E6%9D%BF)，[页面归档](https://web.archive.org/web/20190909141018/https://extmool.github.io/about/) 创建于 UTC+8 2019-09-09 22:10:18

您好。首先，您看到我的博客中注明的CC BY-NC-ND 4.0 协议，是在我近期（三天前）更新NexT主题至7.1.2版本后修改的，此时距离我撤下相关博文已超过1个月（本issue中我于8月1日发出相关评论）

其次，extmool对我进行的警告是不合法的。并不存在所谓的“CC BY-NC-SA 4.0 （不可演绎）”协议，“不可演绎”仅适用于CC BY-NC-ND与CC BY-ND两种协议

所以他对我的警告无效

第三，正如您在extmool的about中所说，如果用户阅读文章的过程中无法看到关于版权协议的注明，这个协议也就是无效的。我可以保证，而且现在也可以进行操作记录，在访问extmool博客的首页，归档，分类，标签以及about页面（不拉到最底部）和所有文章界面时，我并没有看到关于此协议的声明，所以，就像我在博客背景后面遮盖住一段"本文全文禁止复制/转载"一样，如果我不能在正常操作的情况下看到此协议，就是无效的。

第四，需要您明确一点：在我浏览文章时，没有出现的协议均对我无约束力

您不要信口开河。我可以证明，extmool的关于界面的协议说明是于2019年8月1日13:20:26发布的，这点从github的commit history可以看到，[链接在此](https://github.com/extmool/extmool.github.io/commit/af50038e016b5357733b2aab06ae3440a6e89dc0#diff-a7224db13f3a49096aa27c1876d1a947)，截图如下：

![screencapture-github-extmool-extmool-github-io-commit-af50038e016b5357733b2aab06ae3440a6e89dc0-2019-09-09-23_32_03.png](https://i.loli.net/2019/09/09/CnZhEoxNzDyOSGk.png)

如图，放大后可以看到，about/index.html中有如下删改：

```
+ <p>本博客中所有文章除在文章中特别声明者外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">[CC BY-NC-SA 4.0]</a> 许可协议，转载请注明出处。</p>
```

而其在此issue中对我评论的时间是在2019年8月1日12:54，这说明就在其对我评论之时，仍然没有在博客中任何地方声明任何协议

基于此，您的所有反驳都是无效的，因为我有充分的证据证明，在我看到此网页时，以及在extmool回复我时，其均为有任何协议声明。此博文关于修改extmool博客的这一部分是完全合法的

**Comment by code004Accepted** [comment]
@MoveToEx 顺便提醒一句，您的博客触犯了NexT主题的LICENSE，在[这里](https://github.com/theme-next/hexo-theme-next/blob/master/LICENSE.md)可以查看到，原文部分如下：

```
c) A covered work must retain «NexT» official website link (https://theme-next.org) in footer section of every website created, modified or manipulated by using «NexT». «NexT» theme configuration must be:

footer:
  theme:
    enable: true
Collaborators, best contributors and all authors specified in the 'docs/AUTHORS.md' file of «NexT» repository under the 'https://github.com/theme-next' organization can ignore theme info link requirements.
```

我十分相信您不是collaborators, best contributors或者authors，所以也请您遵守NexT的协议

请不要说我管不着，如果我管不着您触犯NexT的协议，您也管不着extmool和我的纠纷
