### ISSUE TITLE
使用C++制作GC Server | code004's Blog

### ISSUE THREAD

**Issue by code004Accepted** [code004Accepted/blog-comment#46]
https://code004.ml/make-your-own-gc-server-with-cpp/#more 

 简介最近很多人找我要GC Server的源代码。我跟他们讲环境要求的时候，很多人都不以为然，结果最后仅仅测试程序就报了几千个Error。所以，我决定今天讲一下如何搭建你自己的GC Server。（目前还没有一个人成功，请量力而行，如果成功了记得在评论区告诉我~）

**Comment by lyonluyuang** [comment]
希望加入Linux(Ubuntu)版

**Comment by code004Accepted** [comment]
> @lyonluyuang
> 希望加入Linux(Ubuntu)版

感谢提醒，移植已经在项目Beta版本的工作计划中，详情请参见[GC Server 分站 相关进度](https://code004.ml/GC-Server/2019/07/31/beta-version-progress/)

同时，欢迎您加入开发，请参见[code004Accepted/GC-Server-dev](https://github.com/code004accepted/GC-Server-dev)

**Comment by code004Accepted** [comment]
最主要的是 图形库貌似并不支持Ubuntu 这个移植的工作量很大，还不一定搞得定qwq

**Comment by lyonluyuang** [comment]
我很乐意，不过可能时间不够。

P.S. Linux可以用GTK+。
