### ISSUE TITLE
分享一下自己平常喜欢用的软件 | code004's Blog

### ISSUE THREAD

**Issue by code004Accepted** [code004Accepted/blog-comment#56]
https://code004.ml/some-softwares-i-like/ 

 分享一下自己平常喜欢用的软件qwq IDE/文本编辑器Microsoft Visual Studio 优点：  在安装的时候可以根据喜好自定义想安装的模块，安装速度快 扩展商店内容多，还可以与Qt连接 项目生成速度快，头文件囊括量大，好像还包括OpenGL 轻松手动复制粘贴需要的全局头文件和lib库 还有图片编辑功能，窗口编辑功能等普通IDE不可能有的功能，且自带HTML语法高亮，亦可以当成文本编

**Comment by Catty2014** [comment]
[Comment from Firefox]
Firefox...很难用吗?
反正我的Firefox,无论是机房安装的,自己的Windows,Arch,都不会弹广告啊
而且Firefox的主要运营是Mozilla,不是国内公司
国内版的运营倒确实还有谋智...
不过也没有那么的不堪吧...

**Comment by code004Accepted** [comment]
> @Catty2014
> [Comment from Firefox]
> Firefox...很难用吗?
> 反正我的Firefox,无论是机房安装的,自己的Windows,Arch,都不会弹广告啊
> 而且Firefox的主要运营是Mozilla,不是国内公司
> 国内版的运营倒确实还有谋智...
> 不过也没有那么的不堪吧...

不是难用，只是习惯了Chrome的浏览器（用了2~3年了），就肯定会不习惯Firefox

肯定也不会那么不堪，我写这篇文章的时候很明显有些偏激 :(

Ubuntu系统里包含了Firefox（而没有Chrome），肯定也能说明一些问题qwq

或许还是习惯原因吧，我主要是觉得Firefox的UI看着不爽（换了主题以后有所改善），还有就是尖角让我很难受（Chrome都是圆角qwq）

**Comment by jerrywcy** [comment]
说实话Cent Browser也很棒啊

**Comment by hmsjy2017** [comment]
推荐Markdown编辑器Typora、开源压缩软件7-Zip和PeaZip、不限速的网盘蓝奏云、免费的PDF编辑器FreePDF、好用的虚拟机VMware Workstation Pro、截图工具Snipaste、轻量SSH工具PuTTY、文件同步用坚果云、下载工具IDM/FDM/XDM
还有好多 不想写了...
