### ISSUE TITLE
关于进入九年级后此博客处理办法的公告 | code004's Blog

### ISSUE THREAD

**Issue by code004Accepted** [code004Accepted/blog-comment#60]
https://code004.ml/posts/notice-about-junior-grade-9/ 

 众所周知，在2019年8月23日（提前开学），本人将正式成为一名初三学生。由于 元月调考/四月调考/中考 这三场考试对每一位考生都意义重大，影响未来命运，现特别给出以下公告： 关于进入九年级后此博客处理办法的公告2019.08.17 01:18:24 公告作者：code004/陈泊锦 因为我即将进入学习紧张的初三，故此博客很可能没有时间来更新。之前的一周23更，现更改为一月12更，感谢谅解。此博客

**Comment by Catty2014** [comment]
Markdown炸啦!
blog.md: 之前的一周2~3更,现更改为一月1~2更
                                   ^                             ^

(一周23更和一月12更还是很勤快的(滑稽

**Comment by code004Accepted** [comment]
> @Catty2014
> Markdown炸啦!
> ```
> blog.md:之前的一周2~3更,现更改为一月1~2更
>                  ^                ^
> ```
> (一周23更和一月12更还是很勤快的(滑稽

感谢提醒，已经修改

（话说刚刚github炸了... 我都是用VPN才能登上去...

**Comment by code004Accepted** [comment]
> @Catty2014
> Markdown炸啦!
> ```
> blog.md:之前的一周2~3更,现更改为一月1~2更
>                  ^                ^
> ```
> (一周23更和一月12更还是很勤快的(滑稽

（对面的分站的gitalk已经炸了，已经都no access token了qwq

**Comment by ldq101** [comment]
我就是洛谷的tarjin，来冒个泡，前排资瓷，楼主看到了回一下呗。

**Comment by code004Accepted** [comment]
@ldq101 Hi233

**Comment by JackMerryYoung** [comment]
烤咕值
