### ISSUE TITLE
关于《CCF关于暂停NOIP竞赛的公告》 | code004's Blog

### ISSUE THREAD

**Issue by code004Accepted** [code004Accepted/blog-comment#61]
https://code004.ml/posts/hack-noi-website/ 

 本文仅供娱乐，请不要断章取义 查看后文前请务必保证您同意下面的协议： 12341. 如果我是NOI/CCF相关工作人员，我保证我不会查看本文的任何内容，并且我保证我不会以任何方式告诉我的同事直接或间接地查看本文，我已知晓本文作者（即博主）不承担本文所造成的任何后果与责任；2. 如果我不是NOI/CCF相关工作人员，我保证我不会以任何方式直接或间接地告知NOI/CCF及相关组织来查看本站/本博文；3

**Comment by code004Accepted** [comment]
这里可以畅所欲言，不用顾虑禁赛的问题qwq

**Comment by wemspzc** [comment]
秀！

**Comment by LV24twx** [comment]
厉害啊

**Comment by jerrywcy** [comment]
秀
天秀
陈独秀
蒂花之秀

**Comment by LV24twx** [comment]
造化钟神秀

**Comment by 1753262762** [comment]
您tQL

**Comment by qq1010903229** [comment]
# xixi tql

**Comment by ciwomuli** [comment]
我只想说，为什么不去刷http://www.moe.gov.cn

**Comment by code004Accepted** [comment]
> @ciwomuli
> 我只想说，为什么不去刷http://www.moe.gov.cn

目前还不敢qwq

**Comment by qq1010903229** [comment]
# xixi 推荐一个软件： #67

**Comment by code004Accepted** [comment]
> # xixi 推荐一个网站： #67

? 您reference #67 干什么qwq
